import type { LocationName, MenuItem } from "@/type";

// 🔴 START: Location and menu data
// Description: Static app menu with location-based pricing for every food item.
export const LOCATIONS: LocationName[] = [
  "Isheri",
  "Lekki",
  "Firstark",
  "Akute",
  "Arepo",
  "Magoro",
];

export const MENU_CATEGORIES: Array<MenuItem["category"]> = [
  "Shawarma",
  "Main Dishes",
  "Grills & Suya",
];

export const MENU_ITEMS: MenuItem[] = [
  {
    id: "1",
    name: "Shawarma Single Sausage",
    category: "Shawarma",
    description: "Tender shawarma with a single sausage, fresh vegetables, and signature sauce.",
    prices: {
      Isheri: 3000,
      Lekki: 3500,
      Firstark: 3200,
      Akute: 3000,
      Arepo: 3100,
      Magoro: 3000,
    },
    image: require("../assets/images/burger-one.png"),
    image_url: "https://via.placeholder.com/720x720.png?text=Shawarma+Single+Sausage",
  },
  {
    id: "2",
    name: "Double Sausage Shawarma",
    category: "Shawarma",
    description: "Two grilled sausages wrapped with veggies and sauces for double the flavor.",
    prices: {
      Isheri: 3500,
      Lekki: 3800,
      Firstark: 3600,
      Akute: 3500,
      Arepo: 3600,
      Magoro: 3500,
    },
    image: require("../assets/images/burger-two.png"),
    image_url: "https://via.placeholder.com/720x720.png?text=Double+Sausage+Shawarma",
  },
  {
    id: "3",
    name: "Extra Chicken Shawarma",
    category: "Shawarma",
    description: "Loaded with extra chicken, fresh herbs, and our spicy sauce.",
    prices: {
      Isheri: 4500,
      Lekki: 4700,
      Firstark: 4600,
      Akute: 4500,
      Arepo: 4600,
      Magoro: 4500,
    },
    image: require("../assets/images/pizza-one.png"),
    image_url: "https://via.placeholder.com/720x720.png?text=Extra+Chicken+Shawarma",
  },
  {
    id: "4",
    name: "Special D’Sauce Shawarma",
    category: "Shawarma",
    description: "Our signature shawarma with special D’Sauce and premium fillings.",
    prices: {
      Isheri: 5000,
      Lekki: 5200,
      Firstark: 5100,
      Akute: 5000,
      Arepo: 5100,
      Magoro: 5000,
    },
    image: require("../assets/images/buritto.png"),
    image_url: "https://via.placeholder.com/720x720.png?text=Special+D%27Sauce+Shawarma",
  },
  {
    id: "5",
    name: "Chops",
    category: "Shawarma",
    description: "Crispy chopped protein wrapped with shawarma spices and veggies.",
    prices: {
      Isheri: 3000,
      Lekki: 3200,
      Firstark: 3100,
      Akute: 3000,
      Arepo: 3050,
      Magoro: 3000,
    },
    image: require("../assets/images/fries.png"),
    image_url: "https://via.placeholder.com/720x720.png?text=Chops",
  },
  {
    id: "6",
    name: "Suya Shawarma",
    category: "Shawarma",
    description: "Spicy suya-flavored shawarma with juicy meat and crisp vegetables.",
    prices: {
      Isheri: 6000,
      Lekki: 6200,
      Firstark: 6100,
      Akute: 6000,
      Arepo: 6100,
      Magoro: 6000,
    },
    image: require("../assets/images/salad.png"),
    image_url: "https://via.placeholder.com/720x720.png?text=Suya+Shawarma",
  },
  {
    id: "7",
    name: "Stir Fry Pasta",
    category: "Main Dishes",
    description: "Creamy stir fry pasta tossed with vegetables and house sauce.",
    prices: {
      Isheri: 2500,
      Lekki: 2700,
      Firstark: 2600,
      Akute: 2500,
      Arepo: 2550,
      Magoro: 2500,
    },
    image: require("../assets/images/cheese.png"),
    image_url: "https://via.placeholder.com/720x720.png?text=Stir+Fry+Pasta",
  },
  {
    id: "8",
    name: "Suya Rice",
    category: "Main Dishes",
    description: "Rice served with tender suya, peppers, and spicy sauce.",
    prices: {
      Isheri: 3000,
      Lekki: 3200,
      Firstark: 3100,
      Akute: 3000,
      Arepo: 3100,
      Magoro: 3000,
    },
    image: require("../assets/images/burger-one.png"),
    image_url: "https://via.placeholder.com/720x720.png?text=Suya+Rice",
  },
  {
    id: "9",
    name: "Asun Rice",
    category: "Main Dishes",
    description: "Peppery asun meat paired with fluffy rice and seasonings.",
    prices: {
      Isheri: 3000,
      Lekki: 3200,
      Firstark: 3100,
      Akute: 3000,
      Arepo: 3100,
      Magoro: 3000,
    },
    image: require("../assets/images/burger-two.png"),
    image_url: "https://via.placeholder.com/720x720.png?text=Asun+Rice",
  },
  {
    id: "10",
    name: "Chinese Rice",
    category: "Main Dishes",
    description: "Wok-fried rice with vegetables, chicken, and savory soy sauce.",
    prices: {
      Isheri: 4000,
      Lekki: 4200,
      Firstark: 4100,
      Akute: 4000,
      Arepo: 4100,
      Magoro: 4000,
    },
    image: require("../assets/images/burger-one.png"),
    image_url: "https://via.placeholder.com/720x720.png?text=Chinese+Rice",
  },
  {
    id: "11",
    name: "Caribbean Rice",
    category: "Main Dishes",
    description: "Tropical rice with bold spices, plantain, and juicy protein.",
    prices: {
      Isheri: 4000,
      Lekki: 4200,
      Firstark: 4100,
      Akute: 4000,
      Arepo: 4100,
      Magoro: 4000,
    },
    image: require("../assets/images/pizza-one.png"),
    image_url: "https://via.placeholder.com/720x720.png?text=Caribbean+Rice",
  },
  {
    id: "12",
    name: "Native Rice",
    category: "Main Dishes",
    description: "Classic native rice with rich stew and garnish.",
    prices: {
      Isheri: 3000,
      Lekki: 3200,
      Firstark: 3100,
      Akute: 3000,
      Arepo: 3100,
      Magoro: 3000,
    },
    image: require("../assets/images/burger-two.png"),
    image_url: "https://via.placeholder.com/720x720.png?text=Native+Rice",
  },
  {
    id: "13",
    name: "Smoky Jollof Rice",
    category: "Main Dishes",
    description: "Flavorful smoky jollof rice served with pepped-up protein.",
    prices: {
      Isheri: 3000,
      Lekki: 3200,
      Firstark: 3100,
      Akute: 3000,
      Arepo: 3100,
      Magoro: 3000,
    },
    image: require("../assets/images/onion-rings.png"),
    image_url: "https://via.placeholder.com/720x720.png?text=Smoky+Jollof+Rice",
  },
  {
    id: "14",
    name: "Full Chicken Suya",
    category: "Grills & Suya",
    description: "Whole grilled chicken seasoned with suya spices and herbs.",
    prices: {
      Isheri: 8000,
      Lekki: 8200,
      Firstark: 8100,
      Akute: 8000,
      Arepo: 8100,
      Magoro: 8000,
    },
    image: require("../assets/images/burger-one.png"),
    image_url: "https://via.placeholder.com/720x720.png?text=Full+Chicken+Suya",
  },
  {
    id: "15",
    name: "Half Chicken Suya",
    category: "Grills & Suya",
    description: "Half roasted chicken with spicy suya glaze and peppers.",
    prices: {
      Isheri: 4000,
      Lekki: 4200,
      Firstark: 4100,
      Akute: 4000,
      Arepo: 4100,
      Magoro: 4000,
    },
    image: require("../assets/images/burger-two.png"),
    image_url: "https://via.placeholder.com/720x720.png?text=Half+Chicken+Suya",
  },
  {
    id: "16",
    name: "BBQ Chicken",
    category: "Grills & Suya",
    description: "Smoky BBQ chicken available at a lower cost in some locations.",
    prices: {
      Isheri: 2000,
      Lekki: 3000,
      Firstark: 2500,
      Akute: 2000,
      Arepo: 2600,
      Magoro: 2000,
    },
    image: require("../assets/images/pizza-one.png"),
    image_url: "https://via.placeholder.com/720x720.png?text=BBQ+Chicken",
  },
  {
    id: "17",
    name: "BBQ Turkey",
    category: "Grills & Suya",
    description: "Roasted turkey with sweet and smoky barbecue flavors.",
    prices: {
      Isheri: 6000,
      Lekki: 6200,
      Firstark: 6100,
      Akute: 6000,
      Arepo: 6100,
      Magoro: 6000,
    },
    image: require("../assets/images/burger-one.png"),
    image_url: "https://via.placeholder.com/720x720.png?text=BBQ+Turkey",
  },
  {
    id: "18",
    name: "BBQ Croaker Fish",
    category: "Grills & Suya",
    description: "Grilled croaker fish with BBQ spices, available in tiered pricing.",
    prices: {
      Isheri: 12000,
      Lekki: 14000,
      Firstark: 13000,
      Akute: 12000,
      Arepo: 15000,
      Magoro: 12000,
    },
    image: require("../assets/images/burger-two.png"),
    image_url: "https://via.placeholder.com/720x720.png?text=BBQ+Croaker+Fish",
  },
  {
    id: "19",
    name: "Asun Meat (Spicy Goat Meat)",
    category: "Grills & Suya",
    description: "Spicy asun meat with peppers, served hot and smoky.",
    prices: {
      Isheri: 3000,
      Lekki: 3200,
      Firstark: 3100,
      Akute: 3000,
      Arepo: 3100,
      Magoro: 3000,
    },
    image: require("../assets/images/mushrooms.png"),
    image_url: "https://via.placeholder.com/720x720.png?text=Asun+Meat",
  },
];

export default {
  categories: MENU_CATEGORIES,
  menu: MENU_ITEMS,
  locations: LOCATIONS,
};
// 🔴 END: Location and menu data
